/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedWorkflowsRouteImport } from './routes/_authenticated/workflows'
import { Route as AuthenticatedMrbRejectionRouteImport } from './routes/_authenticated/mrb-rejection'
import { Route as AuthenticatedCreatePoOrderRouteImport } from './routes/_authenticated/create-po-order'
import { Route as AuthenticatedConversionDecisionRouteImport } from './routes/_authenticated/conversion-decision'
import { Route as AuthenticatedCommercialBatchRejectedRouteImport } from './routes/_authenticated/commercial-batch-rejected'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkflowsRoute = AuthenticatedWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMrbRejectionRoute =
  AuthenticatedMrbRejectionRouteImport.update({
    id: '/mrb-rejection',
    path: '/mrb-rejection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCreatePoOrderRoute =
  AuthenticatedCreatePoOrderRouteImport.update({
    id: '/create-po-order',
    path: '/create-po-order',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversionDecisionRoute =
  AuthenticatedConversionDecisionRouteImport.update({
    id: '/conversion-decision',
    path: '/conversion-decision',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommercialBatchRejectedRoute =
  AuthenticatedCommercialBatchRejectedRouteImport.update({
    id: '/commercial-batch-rejected',
    path: '/commercial-batch-rejected',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/commercial-batch-rejected': typeof AuthenticatedCommercialBatchRejectedRoute
  '/conversion-decision': typeof AuthenticatedConversionDecisionRoute
  '/create-po-order': typeof AuthenticatedCreatePoOrderRoute
  '/mrb-rejection': typeof AuthenticatedMrbRejectionRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/commercial-batch-rejected': typeof AuthenticatedCommercialBatchRejectedRoute
  '/conversion-decision': typeof AuthenticatedConversionDecisionRoute
  '/create-po-order': typeof AuthenticatedCreatePoOrderRoute
  '/mrb-rejection': typeof AuthenticatedMrbRejectionRoute
  '/workflows': typeof AuthenticatedWorkflowsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/commercial-batch-rejected': typeof AuthenticatedCommercialBatchRejectedRoute
  '/_authenticated/conversion-decision': typeof AuthenticatedConversionDecisionRoute
  '/_authenticated/create-po-order': typeof AuthenticatedCreatePoOrderRoute
  '/_authenticated/mrb-rejection': typeof AuthenticatedMrbRejectionRoute
  '/_authenticated/workflows': typeof AuthenticatedWorkflowsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/commercial-batch-rejected'
    | '/conversion-decision'
    | '/create-po-order'
    | '/mrb-rejection'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/sitemap.xml'
    | '/commercial-batch-rejected'
    | '/conversion-decision'
    | '/create-po-order'
    | '/mrb-rejection'
    | '/workflows'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/commercial-batch-rejected'
    | '/_authenticated/conversion-decision'
    | '/_authenticated/create-po-order'
    | '/_authenticated/mrb-rejection'
    | '/_authenticated/workflows'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workflows': {
      id: '/_authenticated/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthenticatedWorkflowsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mrb-rejection': {
      id: '/_authenticated/mrb-rejection'
      path: '/mrb-rejection'
      fullPath: '/mrb-rejection'
      preLoaderRoute: typeof AuthenticatedMrbRejectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/create-po-order': {
      id: '/_authenticated/create-po-order'
      path: '/create-po-order'
      fullPath: '/create-po-order'
      preLoaderRoute: typeof AuthenticatedCreatePoOrderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversion-decision': {
      id: '/_authenticated/conversion-decision'
      path: '/conversion-decision'
      fullPath: '/conversion-decision'
      preLoaderRoute: typeof AuthenticatedConversionDecisionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/commercial-batch-rejected': {
      id: '/_authenticated/commercial-batch-rejected'
      path: '/commercial-batch-rejected'
      fullPath: '/commercial-batch-rejected'
      preLoaderRoute: typeof AuthenticatedCommercialBatchRejectedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommercialBatchRejectedRoute: typeof AuthenticatedCommercialBatchRejectedRoute
  AuthenticatedConversionDecisionRoute: typeof AuthenticatedConversionDecisionRoute
  AuthenticatedCreatePoOrderRoute: typeof AuthenticatedCreatePoOrderRoute
  AuthenticatedMrbRejectionRoute: typeof AuthenticatedMrbRejectionRoute
  AuthenticatedWorkflowsRoute: typeof AuthenticatedWorkflowsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommercialBatchRejectedRoute:
    AuthenticatedCommercialBatchRejectedRoute,
  AuthenticatedConversionDecisionRoute: AuthenticatedConversionDecisionRoute,
  AuthenticatedCreatePoOrderRoute: AuthenticatedCreatePoOrderRoute,
  AuthenticatedMrbRejectionRoute: AuthenticatedMrbRejectionRoute,
  AuthenticatedWorkflowsRoute: AuthenticatedWorkflowsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
